### ISSUE TITLE
Template generator puts index.js in src/api and not in src/api/routes

### ISSUE THREAD

**Issue by alinaradu** [arthurfauq/generator-exprest-api#4]
Hi, 
Don't know where the index.js should be - the one for the routes. 
Currently, it's generated in src/api but the CONTRIBUTING doc states it should be in src/api/routes.
Therefore, my routes are never reached.
Thanks.

**Comment by artfauq** [comment]
Hi,
Sorry for the late response, the index.js should be in `/src/api` as it is currently generated and not as stated in CONTRIBUTING.md which I have just updated.
Thanks for pointing it out 👍
