### ISSUE TITLE
Minimum node version

### ISSUE THREAD

**Issue by YassineElbouchaibi** [arthurfauq/generator-exprest-api#9]
I believe there might be a typo in the `package.json`.

The following :
https://github.com/arthurfauq/generator-exprest-api/blob/afeacf7a0373619e6333cdeb07b5b5414d855391/package.json#L51
should be replaced by : 
```js
 "node": ">= 10.0.0" 
```

As the current LTS versions of node and npm are 14.17.3 and 6.14.13

**Comment by artfauq** [comment]
Thanks for reporting it, fixed it :)
